### ISSUE TITLE
MutationObservers!

### ISSUE THREAD

**Issue by paulirish** [tkambler/whenLive#5]
They were designed for this use case. :)

And it'll be a million times less expensive to use than polling in a rAF loop.

**Comment by tkambler** [comment]
Paul -

Again, thank you for the feedback - it's a tremendous help. While the documentation does not mention this (I will update accordingly), my original goal was to create a solution that was compatible with IE 10 and below. You're obviously right regarding the performance of Mutation Observers. Regardless, there's absolutely no reason why this library should not include support for mutation observers when they are available. They are now available in release 2.0.0. Let me know what you think!

**Comment by paulirish** [comment]
looks good! nice implementation.
