### ISSUE TITLE
Not checking visibility by default

### ISSUE THREAD

**Issue by paulirish** [tkambler/whenLive#6]
Checking for presence in the DOM is one thing, but asking for visibility status means a full recalc of styles on every frame.

It's a costly application and whenLive can end up slowing down the page considerably to make this check.

The visibility check seems nice, but I think it's better to keep it opt-in so your library has minimal perf impact.

**Comment by tkambler** [comment]
Paul - I really appreciate the feedback. Your suggestion has been rolled into release 2.0.0 and is ready to go. Thanks!
